### ISSUE TITLE
Update the recipe 

### ISSUE THREAD

**Issue by nsahoo** [Run2-CMS-BPH/BsToPhiMuMu#8]
The recipe for running the EDAnalyzer should be updated with clear instructions.

**Comment by nsahoo** [comment]
I have updated the recipe locally, but not pushed yet to the official repo. I need to do few tests before pushing finally, I'll do those local tests in next few days.

**Comment by nsahoo** [comment]
@deepaksahoo89 : I was trying to run interactively on PromptReco datasets[1,2], but no event passed the interactive run. Could you please check w/ the EDM root files[3,4] whether you are getting the same result as me ? I remember that it was not having such problems before. 

[1] /DoubleMuonLowMass/Run2016H-PromptReco-v2/AOD
[2] /Charmonium/Run2016H-PromptReco-v2/AOD 
[3] /store/data/Run2016H/DoubleMuonLowMass/AOD/PromptReco-v2/000/281/207/00000/085B3A26-6882-E611-A198-02163E0146A0.root
[4] /store/data/Run2016H/Charmonium/AOD/PromptReco-v2/000/281/207/00000/0042DCF9-6382-E611-ABFD-02163E0133B7.root

**Comment by nsahoo** [comment]
@deepaksahoo89 :  I have made the PR https://github.com/Run2-CMS-BPH/BsToPhiMuMu/pull/10, but I need your confirmation before merging it.

**Comment by deepaksahoo89** [comment]
@nsahoo: Yes, I am having same issue with these two datasets. I tried different files from these two datasets, but no events are passing.There is not any error message . I tested for all other datasets, they are interactively running.

**Comment by nsahoo** [comment]
@deepaksahoo89 : then can you please submit the crab job on these datasets quickly ? Let's see whether it gives any event passing with the full statistics.

**Comment by deepaksahoo89** [comment]
I have submitted the jobs.

**Comment by nsahoo** [comment]
@deepaksahoo89: It looks to me that you don't closely look at the discussions ongoing or the new PRs made. I made a PR #10 which includes the new config files to be used, did you notice that ?
1. could you please put/point the (config) files explicitly which are used for crab jobs on DoubleMuon and Charmonium datasets ? 
2. also mention here the GTs used (in the config files) for these crab jobs.

**Comment by deepaksahoo89** [comment]
@nsahoo 

1.for DoubleMuon and Charmonium datasets I have used https://github.com/nsahoo/Run2-Bs2PhiMM/blob/master/BsToPhiMuMu/python/bstophimumu_Run2016_may8.py and https://github.com/nsahoo/Run2-Bs2PhiMM/blob/master/BsToPhiMuMu/python/bstophimumu_Run2016_DoubleMu4p3_PSI_trk_jul26.py respectively.
2. GT's are "auto:run2_data".

**Comment by nsahoo** [comment]
@deepaksahoo89 : can you please check with the updated config files ?
[1] https://github.com/Run2-CMS-BPH/BsToPhiMuMu/blob/master/python/bstophimumu_Run2016H_PromptReco_LMNRtrk.py
[2] https://github.com/Run2-CMS-BPH/BsToPhiMuMu/blob/master/python/bstophimumu_Run2016H_PromptReco_JPSItrk.py

[1] is for LMNRtrk path to be run on DoubleMuon dataset whereas [2] for JPSitrk path with Charmonium dataset.

The corresponding GTs are already mentioned in the config files.

**Comment by deepaksahoo89** [comment]
@nsahoo for both the cases, it is running without any error. But no events are passing.

**Comment by nsahoo** [comment]
@deepaksahoo89 : I'm very sure that the same scenario will be here also. Anyway it'll be good if you can just submit crab jobs on one dataset at least. BTW, i'm closing this issue now.

**Comment by nsahoo** [comment]
+1
